version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3001:3001"
    depends_on:
      - database
  
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - my_data:/data/db
    ports:
      - "27017:27017"
    
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_SERVICE_URL=http://localhost:3001
    depends_on:
      - server
  
volumes: 
  my_data: 