# pull official base image
FROM node:16.5.0-alpine

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY . .
COPY package.json .
COPY package-lock.json .
RUN npm ci

# expose port
EXPOSE 3001

# start app
CMD ["npm", "start"]